import { useCallback, useRef } from "react";
import { toJpeg } from "html-to-image";
import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const ref = useRef<HTMLDivElement>(null);

  const getBlobFromBase64URI = async (uri: string) => {
    try {
      const base64Response = await fetch(uri);
      const blob = await base64Response.blob();
      return blob;
    } catch (err) {
      return new Blob([], { type: "image/jpeg" });
    }
  };

  const handleSaveImage = useCallback(async () => {
    if (ref.current === null) {
      return;
    }

    try {
      const dataUrl = await toJpeg(ref.current, { cacheBust: true });
      const link = document.createElement("a");
      link.download = "htmlToImage.jpeg";
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error(err);
    }
  }, [ref]);

  const handleShareImage = useCallback(async () => {
    if (ref.current === null) {
      return;
    }

    if (!navigator.canShare) {
      return;
    }

    const dataUrl = await toJpeg(ref.current, { cacheBust: true });
    const blob = await getBlobFromBase64URI(dataUrl);
    const file = new File([blob], "htmlToImage.jpeg", {
      type: blob.type,
    });

    const shareData = {
      title: "HTML to JPEG",
      text: "Web Share API is pretty cool",
      files: [file],
    };

    await navigator.share(shareData);
  }, [ref]);

  return (
    <>
      <Head>
        <title>Share HTML as JPEG using Web Share API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div ref={ref} className="bg-white p-4">
          <h1 className="text-2xl text-red-500">Hello World!</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum nulla
            magnam ducimus nobis excepturi suscipit qui vel accusantium
            voluptate, eligendi quisquam commodi iusto at possimus labore
            facilis et rem illo debitis perspiciatis. Laborum at soluta quod
            explicabo labore non cumque quisquam sunt velit quas! Eius in maxime
            non amet aut sed harum fuga dolor totam enim itaque ea, quod ut
            voluptatum voluptate asperiores quaerat? Laudantium eos, ad dicta
            vel voluptate quae reiciendis tenetur consequuntur perspiciatis odio
            qui, ullam velit facilis voluptates. Ad architecto quia dolorem, vel
            doloremque sit maiores magni aliquam autem non quisquam reiciendis
            ipsa minima molestias doloribus accusantium dignissimos voluptas
            minus pariatur et distinctio veniam inventore sint. Fugit, ipsa qui.
            Officiis, nihil debitis reprehenderit quaerat eius quos, assumenda
            accusamus voluptatem laboriosam dolore repellendus tenetur saepe
            earum sed sapiente illum quibusdam dicta. Error ratione harum, dicta
            itaque quis doloribus perspiciatis corporis dignissimos placeat! In,
            quod perferendis? Optio id eveniet enim molestias deserunt tempora
            dolores quas veritatis! Modi voluptates porro ipsa dignissimos fuga
            saepe blanditiis quidem in tempora beatae aliquam quod officiis quo,
            vitae minima ducimus? Eos, laboriosam ipsa in, dolor nostrum maiores
            quaerat nihil beatae tempore possimus vero soluta quasi suscipit
            quae porro laudantium, quidem eius molestiae vel aliquam adipisci
            culpa. Voluptates amet eius ad! Officiis id architecto quae sequi
            consequatur? Maxime voluptatem tempora facere possimus officia
            dignissimos provident ipsa voluptates enim quas, harum sapiente
            veniam dolorem consectetur, minus delectus accusantium sed, eius
            numquam assumenda reprehenderit perspiciatis nam! Accusantium
            perspiciatis voluptate delectus quas quia, odio mollitia eligendi
            est, dignissimos suscipit nemo saepe dolore sit illo laboriosam
            tempore rerum officia eaque quos, voluptatum libero cumque. At
            voluptatum culpa labore distinctio maxime dicta delectus velit,
            veritatis, rem repudiandae eius perferendis quia iusto eaque
            provident laudantium tenetur tempora similique sunt a nihil deleniti
            modi? Nostrum repellendus autem voluptatibus, dolorum doloribus at
            ipsam.
          </p>

          <br />

          <p className="text-sm text-yellow-500">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem odit
            repellendus, quas tenetur beatae nostrum nihil quasi dolor veritatis
            exercitationem. Aliquam quasi enim accusamus rem quidem delectus
            necessitatibus dignissimos facere.
          </p>
        </div>

        <div className="p-4 flex items-center gap-8">
          <button
            onClick={handleSaveImage}
            className="px-8 py-2 bg-gray-600 text-white rounded"
          >
            Save Image
          </button>
          <button
            onClick={handleShareImage}
            className="px-8 py-2 bg-gray-700 text-white rounded"
          >
            Share Image
          </button>
        </div>
      </main>
    </>
  );
}
